groups:
- name: go-demoapp
  jobs:
  - test
  - minor
  - major
  - build

resources:
- name: git
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}

- name: version
  type: semver
  source:
    driver: git
    uri: {{semver-uri}}
    branch: {{semver-branch}}
    private_key: {{github-concourse-private-key}}
    file: {{semver-file}}
    initial_version: {{semver-initial_version}}

- name: docker
  type: docker-image
  source:
    repository: {{dockerhub-repository}}
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
- name: test
  serial: true
  public: false
  plan:
  - get: git
    trigger: true
  - task: run the test suite
    file: git/ci/tasks/run_tests.yaml

- name: minor
  public: false
  plan:
  - get: version
    trigger: false
    params: {bump: minor}
  - put: version
    params: {file: version/version}

- name: major
  public: false
  plan:
  - get: version
    trigger: false
    params: {bump: major}
  - put: version
    params: {file: version/version}

- name: build
  serial: true
  public: false
  plan:
  - aggregate:
    - get: version
    - get: git
      trigger: true
      passed: [test]

  - put: version
    params:
      bump: patch

  - put: docker
    params:
      build: git
      additional_tags: version/version
